--what is the total revenue generated by male vs female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender
--why customers used a discount but still spent more than the average purchase amount?

select customer_id , purchase_amount
from customer
where discount_applied = 'yes' and purchase_amount >= (select AVG(purchase_amount) from customer) 

-- which are the top 5 products with the highest average review rating?
select item_purchased, ROUND (AVG(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--compare the average purchase amounts between standard and express shipping
select shipping_type,
ROUND (avg(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--do subscribed customers spend more? compare average spend and total revenue betwwen subscribers and non-subscribers

select subscription_status,
count(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

--which 5 products has the highest percentage of purchases with discounts applied?

SELECT 
    item_purchased,
    ROUND(
        (SUM(CASE WHEN TRIM(discount_applied) ILIKE 'yes' THEN 1.0 ELSE 0.0 END) / COUNT(*)) * 100, 
        2
    ) as discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

--segment customers into new,returning and loyal based on their total number of previous purcahse and show the count of each segment.

with customer_type as (
select customer_id, previous_purchases,
case
    when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
	from customer
)
select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment

--what are the top 3 purchased products within each category?
with item_counts as (
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() OVER(partition by category order by count(customer_id)desc) as item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <=3;

--Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status

--what is the revenue contribution of each age group?

select age,
sum(purchase_amount) as total_revenue
from customer
group by age
order by total_revenue desc;